<!DOCTYPE html>
<html>
<head>
<title>VI Joyas</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="robots" content="index,follow" />
<meta name="viewport" content="width=device-width, minimum-scale=0.25, maximum-scale=1.6, initial-scale=1.0" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<?php echo $this->headContent(); ?>
</head>
<body>
	<div class="wrapper">
		<!-- ENCABEZADO -->
        <div class="index-content header">
            <div class="headerMenu mobile">
                <i class="fa fa-bars"></i>
            </div>
			<div class="menu">
				<div class="menuLogo">
					<div id="logo"></div>
				</div>
				<nav>
					<ul>
						<li><a href="/">Inicio</a></li>
						<li><a href="/colecciones">Colecciones</a></li>
						<li><a href="/piezas-unicas">Piezas Unicas</a></li>
						<li><a href="/proyectos">Proyectos</a></li>
						<li class="last"><a href="/contacto">Contacto</a></li>					
					</ul>
				</nav>
				<form id="search">
					<div class="search-input-env">
						<input class="form-control search-input" name="s" placeholder="Search..." value="" type="text">
					</div>
					
					<a class="search-btn" href="#">
						<svg xml:space="preserve" enable-background="new 0 0 512 512" viewBox="0 0 512 512" height="24px" width="24px" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" version="1.1">
							<path d="M460.355,421.59L353.844,315.078c20.041-27.553,31.885-61.437,31.885-98.037 C385.729,124.934,310.793,50,218.686,50C126.58,50,51.645,124.934,51.645,217.041c0,92.106,74.936,167.041,167.041,167.041 c34.912,0,67.352-10.773,94.184-29.158L419.945,462L460.355,421.59z M100.631,217.041c0-65.096,52.959-118.056,118.055-118.056 c65.098,0,118.057,52.959,118.057,118.056c0,65.096-52.959,118.056-118.057,118.056C153.59,335.097,100.631,282.137,100.631,217.041 z" id="search-svg"/>
						</svg>
						<span class="sr-only">Search</span>
					</a>
				</form>
			</div>
        </div>
        <!-- FIN DE ENCABEZADO -->

		<!-- CONTENIDO -->
		<div class="contenido">

            <?php $this->getContent(); ?>
		
		</div>
		<!-- FIN CONTENIDO-->
		
		<div class="clearfix"></div>
		
		<!-- PIE DE PAGINA -->
		<footer class="footer">
			<div id="footer-bottom">
				<div class="container clearfix">
				  <p>VI Joyas | Ciudad Autónoma de Buenos Aires, Argentina | Email: <a href="mailto:info@viorfebreria.com">info@viorfebreria.com</a></p>
				  <p><span>&copy; 2015 | Todos los derechos reservados.</span></p>
				</div>
			</div>
		</footer>
		<!-- FIN PIE DE PAGINA -->
	</div>

<?php echo $this->footerContent(); ?>
</body>
</html>
