
			<div class="background-wrapper">
					 <div id="slider" class="nivoSlider">
						<img src="/public/assets/images/slide1.jpg" data-thumb="/public/assets/images/slide1.jpg" alt="" />
						<!--<img src="/public/assets/images/slide2.jpg" data-thumb="/public/assets/images/slide2.jpg" alt="" title="This is an example of a caption" />-->
						<img src="/public/assets/images/slide2.jpg" data-thumb="/public/assets/images/slide2.jpg" alt=""/>
						<img src="/public/assets/images/slide3.jpg" data-thumb="/public/assets/images/slide3.jpg" alt="" data-transition="slideInLeft" />
						<img src="/public/assets/images/slide4.jpg" data-thumb="/public/assets/images/slide4.jpg" alt="" />
					</div>
			</div>
			
			
			<div class="index-content">
				<div class="text-quienes-somos">
					<h3>Quines Somos?</h3>
					<p>
						VI nace con el objetivo de representar nuertros profundos y permanentes deseos de vivir en armonia entre nosotros mismos y el mundo exterior. Encontramos que através del arte la armonia se practica a cada instante y con ella la inspiración se convierte en producto. Trabjar con metales y las gemmas es fruto de nuestro más adorado deleite. Cada obra está construida con amor incondicional a la vida y sólo pretende encontrar a alguién que disfrute de portarla. VI es el conjunto de la voluntad de seres que se sumaron a hacer posible este sueño, que trae tanto poder como disfrute. Y bienvenidos a esta realidad.
				   </p>
				</div>
			</div>
			
            <div class="index-content tituloCatalogo">
				<h2>Novedades<small>Ultimos productos</small></h2>
			</div>
			
			<div class="index-content catalogoProductos ultimosProductos">
				<ul>
					<li>
						<a href="#"><div class="imagen">
							<img src="/public/assets/contenido/colecciones/patagonia-viva/thumbs/Agata_p925_o18.01.jpg" />
						</div>
						</a>
						<div class="caracteristicas">
							<h3>anillo de oro</h3>
							<p>baniado en chocolate</p>
						</div>
					</li>
					<li>
						<div class="imagen">
							<img src="/public/assets/contenido/colecciones/patagonia-viva/thumbs/Agata_p925_o18.02.jpg" />
						</div>
						<div class="caracteristicas">
							<h3>anillo de oro</h3>
							<p>baniado en chocolate</p>
						</div>
					</li>
					<li>
						<div class="imagen">
							<img src="/public/assets/contenido/colecciones/patagonia-viva/thumbs/Agata_p925_o18.03.jpg" />
						</div>
						<div class="caracteristicas">
							<h3>anillo de oro</h3>
							<p>baniado en chocolate</p>
						</div>	
					</li>
					<li>
						<div class="imagen">
							<img src="/public/assets/contenido/colecciones/patagonia-viva/thumbs/Agata_p925_o18.04.jpg" />
						</div>
						<div class="caracteristicas">
							<h3>anillo de oro</h3>
							<p>baniado en chocolate</p>
						</div>
					</li>
										<li>
						<div class="imagen">
							<img src="/public/assets/contenido/colecciones/cualidades/thumbs/Agata_Verde_p925.jpg" />
						</div>
						<div class="caracteristicas">
							<h3>anillo de oro</h3>
							<p>baniado en chocolate</p>
						</div>
					</li>
					<li>
						<div class="imagen">
							<img src="/public/assets/contenido/colecciones/cualidades/thumbs/Amatista_p925.jpg" />
						</div>
						<div class="caracteristicas">
							<h3>anillo de oro</h3>
							<p>baniado en chocolate</p>
						</div>
					</li>
					<li>
						<div class="imagen">
							<img src="/public/assets/contenido/colecciones/cualidades/thumbs/Cuarzo_Rutilado_p925.jpg" />
						</div>
						<div class="caracteristicas">
							<h3>anillo de oro</h3>
							<p>baniado en chocolate</p>
						</div>	
					</li>
					<li>
						<div class="imagen">
							<img src="/public/assets/contenido/colecciones/cualidades/thumbs/Dendrita_p92.jpg" />
						</div>
						<div class="caracteristicas">
							<h3>anillo de oro</h3>
							<p>baniado en chocolate</p>
						</div>
					</li>
				</ul>
				<div class="clearfix"></div>
			</div>

