

		<div class="background-wrapper">
			<img src="/public/assets/images/paracontacto.jpg">
		</div>

        <div class="index-content" id="contactPage">
			<form novalidate="" action="" enctype="application/x-www-form-urlencoded" method="post" id="contact-form">

				<input type="hidden" value="312" name="id">

				<div class="contact-page">
					<div class="row">
						<div class="col-lg-7 col-md-7 col-sm-6">
							<div class="page-title">
								<h3>
									Get in Touch						
									<small>Write us a Letter</small>
								</h3>
							</div>

							<div class="form-success-message hidden">
								<div role="alert" class="alert alert-success">Your message has been sent. We will respond to your request as soon as possible.</div>
							</div>

							<div class="contact-form">
								<div class="row">
									<div class="col-lg-6">
										<div class="form-group">
											<input type="text" class="form-control required" placeholder="Name *" name="name">
										</div>
									</div>
									<div class="col-lg-6">
										<div class="form-group">
											<input type="text" class="form-control required" placeholder="Subject *" name="subject">
										</div>
									</div>
								</div>

								<div class="form-group">
									<input type="email" class="form-control required" placeholder="E-mail *" name="email">
								</div>

								<div class="form-group">
									<textarea rows="5" class="form-control required" placeholder="Message *" name="message"></textarea>
								</div>

								<button class="btn btn-primary send-message pull-right" type="submit">Send Message</button>
							</div>
						</div>
						<div class="col-lg-5 col-md-5 col-sm-6 contact-information">
							<div class="page-title">
								<h3>
									Our Address						
									<small>Where are we located</small>
								</h3>
							</div>

							<p>2954 Golden Estates,<br>
								Guys Store, Virginia,<br>
								24318-5414,<br>
								United states</p>
								<p>(571) 400-1255<br>
								info@aurumtheme.com</p>
								<ul class="social-networks">
									<li><a target="_blank" title="Facebook" href="https://www.facebook.com/laboratorcreative"><i class="entypo-facebook"></i></a></li>
									<li><a target="_blank" title="Twitter" href="https://twitter.com/thelaborator"><i class="entypo-twitter"></i></a></li>
									<li><a target="_blank" title="Google+" href="#googleplus"><i class="entypo-gplus"></i></a></li>
									<li><a target="_blank" title="Vimeo" href="#vimeo"><i class="entypo-vimeo"></i></a></li>
									<li><a target="_blank" title="Pinterest" href="#pinterest"><i class="entypo-pinterest"></i></a></li>
									<li><a target="_blank" title="LinkedIn" href="#linkedin"><i class="entypo-linkedin"></i></a></li>
									<li><a target="_blank" title="Dribbble" href="http://dribbble.com/artramadani"><i class="entypo-dribbble"></i></a>
									</li>
								</ul>
								
						</div>
					</div>
				</div>
			</form>
        </div>

