<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Administrador</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Avant">
    <meta name="author" content="The Red Team">

    <!-- <link href="assets/less/styles.less" rel="stylesheet/less" media="all"> -->
    <link rel="stylesheet" href="/media/site/assets/css/styles.min.css">
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600' rel='stylesheet' type='text/css'>
    
    <!-- <script type="text/javascript" src="less.js"></script> -->
</head>
<body class="focusedform">
<div class="verticalcenter">
    <!--    <a href="index.php"><img src="assets/img/logo-big.png" alt="Logo" class="brand" /></a> -->
    <div class="panel panel-primary">
        <div class="panel-body">
            <!-- <h4 class="text-center" style="margin-bottom: 25px;">Log in to get started or <a href="extras-signupform.php">Sign Up</a></h4> -->
            <h4 class="text-center" style="margin-bottom: 25px;">Ingresar al panel de administración</h4>
                <form action="/admin/auth/login" class="form-horizontal" style="margin-bottom: 0px !important;" id="loginform" method="POST">
                        <div class="form-group">
                            <div class="col-sm-12">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-user"></i></span>
                                    <input name="usuario" type="text" class="form-control" id="username" placeholder="Username">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-12">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                                    <input name="password" type="password" class="form-control" id="password" placeholder="Password">
                                </div>
                            </div>
                        </div>

<!--
                        <div class="clearfix">
                            <div class="pull-right"><label><input type="checkbox" style="margin-bottom: 20px" checked=""> Recordarme</label></div>
                        </div>
-->

                    </form>
                    
        </div>

        <div class="panel-footer">
            <!-- <a href="extras-forgotpassword.php" class="pull-left btn btn-link" style="padding-left:0">Forgot password?</a> -->
            
            <div class="pull-right">
                <a href="#" class="btn btn-default">Reset</a>
                <a href="#" onclick="javascript:document.getElementById('loginform').submit()" class="btn btn-primary">Log In</a>
            </div>
        </div>
    </div>
 </div>
      
</body>
</html>
